#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Display variables used for the Dmenu
export DISPLAY_WIDTH=$(xdpyinfo | grep -oP 'dimensions:\s+\K\S+' | cut -d 'x' -f1)
export DMENU_PAD="9"
export DMENU_WIDTH="$(($DISPLAY_WIDTH - 2 * $DMENU_PAD))"
export DMENU_FONT="SauceCodePro Nerd Font-9"

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
# picom &		        # picom for transparency
# xcompmgr &		        # xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
